function withValidProperties(properties: Record<string, undefined | string | string[] | boolean>) {
  return Object.fromEntries(
    Object.entries(properties).filter(([, value]) => {
      if (typeof value === 'boolean') return true; // Keep all boolean values
      if (Array.isArray(value)) return value.length > 0;
      return !!value;
    })
  );
}

export async function GET() {
  const URL = process.env.NEXT_PUBLIC_URL || 'https://app.muscadine.io';

  const manifest = {
  "accountAssociation": {
    "header": "eyJmaWQiOjIwNjQzNywidHlwZSI6ImF1dGgiLCJrZXkiOiIweDMxRTcwZjA2M2NBODAyRGVkQ2Q3NmU3NEM4RjZENzMwZUM0M0Q5ZjAifQ",
    "payload": "eyJkb21haW4iOiJhcHAubXVzY2FkaW5lLmlvIn0",
    "signature": "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARFrLpzo1d5FWY_d0sjw45fWTdduJxQ3UY20I3WyBAm_ahd-EhTTvGh3-t8Lhu_4c5zydqSrFMfCDXcbqdoFY_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAvuuuB293mod6v05ZFbpPOO6cLIvhWwqMROytRWUz0BEOrSzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABRErBzBhE5GckWGsM_XoKtsDAxSapJwnCn_jntSRCQ-tQpT8bJ665IXcCIOe3tX4R6gjca6q-G4QXw8Z2pDwzwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiV2tlTHFwOUg1RGtUaU05YkRTQnFnRk5sa3BMUEhRNFNhak11dXZoRTF4SSIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS"
  }
}
    miniapp: withValidProperties({
      version: '1',
      name: 'Muscadine Earn',
      homeUrl: URL,
      iconUrl: `${URL}/favicon.png`,
      splashImageUrl: `${URL}/favicon.png`,
      // eslint-disable-next-line no-restricted-syntax
      splashBackgroundColor: '#000000', // Base mini app requires hex color, not CSS variable
      webhookUrl: process.env.NEXT_PUBLIC_WEBHOOK_URL || '',
      subtitle: 'DeFi Vaults on Base',
      description: 'Access Muscadine Vaults.',
      screenshotUrls: [
        // Add screenshot URLs when available
      ],
      primaryCategory: 'finance',
      tags: ['defi', 'vaults', 'yield', 'base', 'muscadine'],
      heroImageUrl: `${URL}/favicon.png`,
      tagline: 'Earn yield on Base',
      ogTitle: 'Muscadine Earn',
      ogDescription: 'Access Muscadine Vaults and earn yield on your assets.',
      ogImageUrl: `${URL}/favicon.png`,
      noindex: false,
    }),
  };

  return Response.json(manifest);
}

